name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deploy on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Use the Node.js version your project supports
      
      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the app with webpack
      - name: Build app with webpack
        run: npm run build  # Assumes your package.json has a 'build' script

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Path to your build directory
